### ISSUE TITLE
The example should check SHA of curl-check-install

### ISSUE THREAD

**Issue by jpap** [antoineco/curl-check-install#1]
Nice tool; I've been writing it by hand myself, too.

I would recommend your example also assert the SHA of the `curl-check-install` download, otherwise it would subject users to a MITM and defeat the whole purpose of the script.  Turtles!

**Comment by antoineco** [comment]
Nice suggestion, and glad you find it useful 👍  
I'm adding that right away.

**Comment by jpap** [comment]
Your commit is still vulnerable to a MITM -- if an attacker were to intercept your HTTPS download with an intermediate server (you're not checking the cert for `raw.githubusercontent.com`), they could serve up a compromised `curl-check-install` script that always returns 0... and therefore your solution is useless.

What you need to do is check the SHA manually the first time.

**Comment by antoineco** [comment]
I did write the checksum manually in the Dockerfile. If the script is altered in any way the checksum won't match and the build will fail. Of course it's your responsibility to check beforehand that you're using the expected checksum in your own Dockerfile.

Regarding the certificate, the Docker client is taking care of fetching the remote file at that point (cf the Dockerfile reference for the `ADD` command). Whether it verifies the certificate or not I'm not sure, but it's the best you can do using that method.

**Comment by jpap** [comment]
> I did write the checksum manually in the Dockerfile. If the script is altered in any way the checksum won't match and the build will fail. Of course it's your responsibility to check beforehand that you're using the expected checksum in your own Dockerfile.

That's good; no issue here.

> Regarding the certificate, the Docker client is taking care of fetching the remote file at that point (cf the Dockerfile reference for the ADD command). Whether it verifies the certificate or not I'm not sure, but it's the best you can do using that method.

You have two options:

1. Verify the HTTPS certificate is from the intended host and not some imposter (a MITM).
1. Verify that the download is correct by SHA, without relying on whatever is provided to you by the remote HTTPS server.

On (1), while Docker will verify that the HTTPS server is using a valid certificate (signed by a root CA), it does **not** verify that it is indeed run by GitHub, Inc..  While it's difficult for someone to get a signed CA without proving ownership of that domain, it's generally a good idea not make the assumption.  Since you're not checking the certificate CN/SAN, you should be following (2).

On (2), you can't rely on a check provided by the content downloaded from the HTTPS server.  That content could be compromised by a MITM (see (1)), and the downloaded script, having been modified by a MITM, could always return 0 ("everything is fine") when in fact the SHA256 is wrong.

Not to be mean, but I would further suggest:

* Adding a disclaimer to your README that suggests your solution hasn't been audited, is not written by a security professional, and that they should rely on the guidance provided at their own risk.  
* Adding a version number into the filename; if you update your script, everyone's build gets broken (assuming they implement (2) above properly).

I'm afraid I'm going to stick to my short code snippet...

**Comment by antoineco** [comment]
Thanks for the feedback, what you say is absolutely true. However the sole purpose of this repo is to provide a convenience script and a usage example which is understandable by anyone.

It seems like you would have expected to find a long 101 on cyber-security attached to the README but this repo is simply not the place for that. Yes, this is Github, this is public, this is open source. Same holds true for every project on the platform I'm afraid.

**Comment by jpap** [comment]
> Thanks for the feedback, what you say is absolutely true. However the sole purpose of this repo is to provide a convenience script and a usage example which is understandable by anyone.

It's rather inconvenient to follow bad advice (and/or implementation) that opens your systems to being compromised.

> It seems like you would have expected to find a long 101 on cyber-security attached to the README but this repo is simply not the place for that. Yes, this is Github, this is public, this is open source. Same holds true for every project on the platform I'm afraid.

Untrue.  As a user, you can opt not to use it -- and that's what I'm going to do.  However all OSS projects benefit from users pointing out bugs, suggesting improvements, etc.  And that's precisely what has happened here.  The suggestion for adding a disclaimer follows -- it may help other users evaluate whether they decide to opt into using it (or not).

In any case, the fix here is rather straightforward.  I wish you all the best with the project.

**Comment by antoineco** [comment]
Why not sending a PR then? I value every opinion and contribution.
